sudo: required

language: android
jdk: oraclejdk8

addons:
    artifacts: true

services:
    - docker

before_install:
    - docker pull circleci/android:api-29-ndk
    - chmod -R a+wrx .

script:
    - docker run --rm -v ${PWD}:/build circleci/android:api-29-ndk bash -c "cd /build; ./gradlew assembleDebug check"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: $github_token
  file_glob: true
  file: ${PWD}:/build/matdesign/app/build/outputs/apk/release/*
  on:
    repo: elsadeny/matdesign
    tags: true
