sudo: required

language: android
jdk: oraclejdk8

addons:
    artifacts: true

services:
    - docker

before_install:
    - docker pull circleci/android:api-29-ndk
    - chmod -R a+wrx .

script:
    - docker run --rm -v ${PWD}:/build circleci/android:api-29-ndk bash -c "cd /build; ./gradlew assembleRelease check"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api-key: $github_token
  file_glob: true
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/*
  on:
    repo: elsadeny/matdesign
    tags: true
after_deploy:
    -rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
